---
# tasks file for etcd

- import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - etcd

- import_tasks: centos.yml
  when: ansible_distribution == "CentOS"
  tags:
    - etcd

- name: Service unit
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: 
    - daemon reload
    - start etcd 
    - restart etcd 
  tags:
    - etcd
  


  