kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: geIdTBg/c3fJKs1h3lQ4K7FrwYFrqYS3QxroR+2BErw=
      - identity: {}

kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
    - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: MXDV6KcPOUIW/cu3MyNeKpiAgByb3KcbYH3STgW+LbU=
      - identity: {}