---
- name: Centos - Configure Kubernetes Repository
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Centos - Install kubernetes packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - "kubelet-{{ kubernetes_version }}"
      - "kubeadm-{{ kubernetes_version }}"
      - "kubectl-{{ kubernetes_version }}"
