# tasks file for kubernetes
- name: Ubuntu - Add apt key for kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present


- name: Ubuntu - Add kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Ubuntu - Install kubernetes packages
  apt:
    pkg:
    - "kubelet={{ubuntu_kubernetes_version}}"
    - "kubeadm={{ubuntu_kubernetes_version}}"
    - "kubectl={{ubuntu_kubernetes_version}}"
  when:  "'tag_role_kubes' in group_names"

- name: Ubuntu - Install kubectl only
  apt:
    pkg:
    - "kubectl={{ubuntu_kubernetes_version}}"
  when: "'tag_role_ctrl' in group_names"

