kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: kqjUVfcL7fg3rsOX8BsXGMXeabuNyCpWs+XqSqr+oug=
      - identity: {}
