---
# tasks file for worker

- name: Create kubernetes folder
  file:
    path: /opt/kubernetes
    state: directory

- name: Install socat, conntrack, ipset
  apt:
    pkg:
    - socat
    - conntrack
    - ipset

- name: Stat cri tools
  stat:
    path: "/opt/crictl-{{crit_tools_version}}-linux-amd64.tar.gz"
  register: r_cri_tools

- name: Get cri-tools
  get_url:
    url: "https://github.com/kubernetes-incubator/cri-tools/releases/download/{{crit_tools_version}}/crictl-{{crit_tools_version}}-linux-amd64.tar.gz"
    dest: /opt/
  when: r_cri_tools.stat.exists == False

- name: Get runsc
  get_url:
    url: "https://storage.googleapis.com/kubernetes-the-hard-way/runsc"
    dest: /opt/kubernetes/

- name: Get runc
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/v1.0.0-rc5/runc.amd64"
    dest: /opt/kubernetes/

- name: Get cni plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v0.6.0/cni-plugins-amd64-v0.6.0.tgz"
    dest: /opt/kubernetes/