---
# tasks file for kube-master

- name: Create etc directories
  file: 
    path: "{{item}}"
    state: directory
  with_items:
    - /etc/etcd 
    - /var/lib/etcd

- name: copy pem files to etcd dir
  copy:
    src: "{{ item }}"
    dest: /etc/etcd
  with_items:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem

- name: stat etcd binaries
  stat:
    path: "/opt/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
  register: r_etcd_bin

- name: Get etcd package
  get_url: 
    url: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: "/opt/"
  when: r_etcd_bin.stat.exists == False

- name: Extract etcd package
  unarchive:
    src: "/opt/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /opt/
    remote_src: yes

- name: Link binaries 
  file:
    src: "/opt/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - etcd
    - etcdctl

- name: Create etcd unit file
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd

- name: Enable etcd
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes    

- name: Create config file
  template:
    src: config.yaml.j2
    dest: /home/ubuntu/config.yaml