---
# tasks file for kube-member

#- debug:
#    var: hostvars[groups.tag_master[0]].ansible_default_ipv4.address


- name: Join to master kube node
  shell: "kubeadm join {{hostvars[groups.tag_master[0]].ansible_default_ipv4.address}}:6443 --token {{k_token}} --discovery-token-ca-cert-hash {{k_hash}}"
  register: r_kubeadm_join 
  when:
    - "'tag_member' in group_names"   
  tags:
    - setup_members

- name: Print kudamdm join output
  debug:
    var: r_kubeadm_join
  when:
    - "'tag_member' in group_names"   
  tags:
    - setup_members  

- name: Turn on iptables bridge calls 
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
    sysctl_set: yes
  tags:
    - setup_cluster_networking

- name: Install flannel networking on master
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml"
  register: r_kubeadm_join 
  when:
    - "'tag_master' in group_names"   
  tags:
    - setup_cluster_networking