- hosts: tag_role_kube-master:tag_role_lb-kube
  gather_facts: true

- hosts: tag_role_ctrl
  become: true
  gather_facts: true
  roles:
    - ctrl
    - kubernetes
  vars:
    ubuntu_kubernetes_version: "1.17.0-00"
