- hosts: all
  become: true
  gather_facts: true
  roles:
    - etcd
    - docker 
    - kubernetes
  vars:
    etcd_version: "v3.3.18"
    ubuntu_kubernetes_version: "1.17.0-00"
    ubuntu_docker_version: "18.06.1~ce~3-0~ubuntu"
