#- hosts: tag_role_kube-master
#  become: true
#  gather_facts: true
#  roles:
#    - etcd
#    - kube-master
#  vars:
#    etcd_version: "v3.3.18"
#    kubernetes_release: "v1.10.2"


- hosts: tag_role_kube-worker
  become: true
  gather_facts: true
  roles:
    - kube-worker
  vars:
    crit_tools_version: "v1.0.0-beta.0"



