---
# tasks file for setip

- name: Find and replace bootproto
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    regexp: '^BOOTPROTO=\"dhcp\"'
    replace: |-
      BOOTPROTO="static"

- name: Prefix
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    state: present
    regexp: '^PREFIX'
    line: 'PREFIX={{prefix}}'

- name: Address
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    state: present
    regexp: '^IPADDR'
    line: 'IPADDR={{static_address}}'

- name: Gateway
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    state: present
    regexp: '^GATEWAY'
    line: 'GATEWAY={{static_gateway}}'

- name: DNS1
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    state: present
    regexp: '^DNS1'
    line: 'DNS1=8.8.8.8'

- name: DNS2
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens33
    state: present
    regexp: '^DNS2'
    line: 'DNS2=8.8.4.4'


